# Generated by Django 5.1.8 on 2025-04-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hr_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to='companydetails.companyemployee'),
        ),
    ]
