# Generated by Django 5.1.8 on 2025-04-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companydetails', '0002_candidate_hr_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='hr_assigned',
            new_name='assigned_hr',
        ),
    ]
