# Generated by Django 5.1.8 on 2025-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companydetails', '0004_alter_accessemployee_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemployee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
